export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SET_USER_BEGIN = 'SET_USER_BEGIN'
export const SET_USER_SUCCESS = 'SET_USER_SUCCESS'
export const SET_USER_ERROR = 'SET_USER_ERROR'